package com.voyager.voyager_station.gui;

import com.voyager.voyager_station.jdbc.PasswordRooms;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Roberto Maffucci
 */
public class ComputerGUI extends javax.swing.JFrame {

    private GUI gui;

    private final String COMPUTER_PASSWORD = "346871";

    /**
     * Creates new form ComputerGUI
     */
    public ComputerGUI() {
        initComponents();
    }

    public ComputerGUI(GUI gui) {
        initComponents();
        this.gui = gui;
        init();
    }

    private void init() {
        lblBackground.setIcon(new ImageIcon("./resources/img/computerGUI.jpg"));
        txtNameCamera.setEnabled(false);
        btnPassword.setEnabled(true);
        btnRoom.setEnabled(false);
        btnPassword.addActionListener(new PasswordAction());
        jPasswordField.setAction(new PasswordAction());
        btnRoom.addActionListener(new SearchRoomAction());
        txtNameCamera.addActionListener(new SearchRoomAction());
    }

    protected class PasswordAction extends AbstractAction {

        @Override
        public void actionPerformed(ActionEvent e) {
            insertPassword();
        }
    }

    protected class SearchRoomAction extends AbstractAction {

        @Override
        public void actionPerformed(ActionEvent e) {
            searchRoom();
        }
    }

    private void insertPassword() {
        if (Arrays.equals(COMPUTER_PASSWORD.toCharArray(), jPasswordField.getPassword())) {
            txtNameCamera.setEnabled(true);
            btnRoom.setEnabled(true);
            jPasswordField.setEnabled(false);
            btnPassword.setEnabled(false);
        } else {
            jPasswordField.setText("");
            JOptionPane.showMessageDialog(null, "La password inserita non è corretta! Riprovare.", "Errore password", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void searchRoom() {
        try {
            String password;
            PasswordRooms.getInstance().connect();
            if (!txtNameCamera.getText().isEmpty()) {
                password = PasswordRooms.getInstance().searchRoomPassword(txtNameCamera.getText().toLowerCase());
                if (password != null) {
                    txtPasswordRoom.setText(password);
                } else {
                    JOptionPane.showMessageDialog(null, "Nessuna camera disponibile", "Camera inesistente", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Nessuna camera inserita!", "Camera non specificata", JOptionPane.ERROR_MESSAGE);
            }
            PasswordRooms.getInstance().disconnect();
        } catch (SQLException ex) {
            Logger.getLogger(ComputerGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtPasswordRoom = new javax.swing.JTextArea();
        btnRoom = new javax.swing.JButton();
        txtNameCamera = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPassword = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Codici accesso stanze bloccate");
        setBackground(new java.awt.Color(0, 153, 153));
        setFocusable(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtPasswordRoom.setColumns(20);
        txtPasswordRoom.setRows(5);
        txtPasswordRoom.setAutoscrolls(false);
        jScrollPane2.setViewportView(txtPasswordRoom);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 225, 32));

        btnRoom.setBackground(new java.awt.Color(31, 117, 203));
        btnRoom.setForeground(new java.awt.Color(255, 255, 255));
        btnRoom.setText("CERCA PASSWORD");
        btnRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRoom.setName("nameRoom"); // NOI18N
        getContentPane().add(btnRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 180, -1));
        getContentPane().add(txtNameCamera, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 180, 23));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password Terminale");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 179, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome stanza:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password stanza:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        btnPassword.setBackground(new java.awt.Color(31, 117, 203));
        btnPassword.setForeground(new java.awt.Color(255, 255, 255));
        btnPassword.setText("INVIA");
        btnPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPassword.setName("nameRoom"); // NOI18N
        getContentPane().add(btnPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 180, -1));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPassword;
    private javax.swing.JButton btnRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JTextField txtNameCamera;
    private javax.swing.JTextArea txtPasswordRoom;
    // End of variables declaration//GEN-END:variables
}
